const actions = {
    // GENERAL
    ON_CATCH_ERROR: 'ON_CATCH_ERROR',
    ON_SET_LOADING: 'ON_SET_LOADING',
    ON_SET_LOADING_LAZY: 'ON_SET_LOADING_LAZY',

    // LOCALIZATION
    CHANGE_LOCATION: 'CHANGE_LOCATION',
    CHANGE_LANG: 'CHANGE_LANG',
    CHANGE_SEARCH_LOC: 'CHANGE_SEARCH_LOC',
    ON_SEARCH_INPUT: 'ON_SEARCH_INPUT',
    
    // FILTERS
    ON_FILTER_BY_COUNTERS: 'ON_FILTER_BY_COUNTERS',
    ON_FILTER_BY_OPTIONS: 'ON_FILTER_BY_OPTIONS'
};

export default actions;