const actions = {
    // GENERAL
    ON_CATCH_ERROR: 'ON_CATCH_ERROR',
    ON_SET_LOADING: 'ON_SET_LOADING',
    ON_SET_LOADING_LAZY: 'ON_SET_LOADING_LAZY',
    FETCH_DATA_SUCCESS: 'FETCH_DATA_SUCCESS',

    // LOCALIZATION
    CHANGE_LOCATION: 'CHANGE_LOCATION',
    CHANGE_LANG: 'CHANGE_LANG',
    CHANGE_SEARCH_LOC: 'CHANGE_SEARCH_LOC',
    ON_SEARCH_INPUT: 'ON_SEARCH_INPUT',
    
    // MAIN DATA
    FETCH_FOR_HOMEPAGE: 'FETCH_FOR_HOMEPAGE',
    FETCH_FOR_MAIN: 'FETCH_FOR_MAIN',
    

};

export default actions;