const actions = {
    // GENERAL
    ON_CATCH_ERROR: 'ON_CATCH_ERROR',
    ON_SET_LOADING: 'ON_SET_LOADING',
    ON_MATCH_SMALL_MEDIA: 'ON_MATCH_SMALL_MEDIA',

    // USER
    ON_SET_FAVORITES: 'ON_SET_FAVORITES',
    ON_LOG_IN: 'ON_LOG_IN',
    ON_LOG_OUT: 'ON_LOG_OUT',

    // LOCALIZATION
    CHANGE_LOCATION: 'CHANGE_LOCATION',
    CHANGE_LANG: 'CHANGE_LANG',
    CHANGE_SEARCH_LOC: 'CHANGE_SEARCH_LOC',
    ON_SEARCH_INPUT: 'ON_SEARCH_INPUT',
    IMPORT_REQUISITES: 'IMPORT_REQUISITES',
    ADD_SEARCH_LOCATION: 'ADD_SEARCH_LOCATION',
    ON_SET_LOADING_MAIN: 'ON_SET_LOADING_MAIN',
    
    // FILTERS
    ON_FILTER_BY_COUNTERS: 'ON_FILTER_BY_COUNTERS',
    ON_FILTER_BY_OPTIONS: 'ON_FILTER_BY_OPTIONS'
};

export default actions;